import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import type { DocumentSection } from "./types";
import type { AnnexureTemplate } from "./annexures";

interface DocumentPreviewProps {
  title: string;
  sections: DocumentSection[];
  annexures?: AnnexureTemplate[];
}

export function DocumentPreview({ title, sections, annexures = [] }: DocumentPreviewProps) {
  return (
    <ScrollArea className="flex-1 rounded-2xl">
      <div className="mx-auto max-w-3xl p-8 md:p-12">
        <article className="rounded-2xl border border-border bg-nit-paper p-8 shadow-nit md:p-12">
          <header className="mb-10 text-center">
            <h1 className="text-2xl font-semibold tracking-tight text-foreground md:text-3xl">
              {title}
            </h1>
            <p className="mt-2 text-sm font-medium uppercase tracking-widest text-muted-foreground">
              Procurement Document
            </p>
          </header>

          <Separator className="mb-10" />

          <div className="space-y-10">
            {sections.map((section, index) => (
              <section key={index}>
                <h2 className="mb-3 text-base font-semibold tracking-tight text-foreground">
                  {index + 1}. {section.title}
                </h2>
                <div className="space-y-3 text-sm leading-relaxed text-muted-foreground">
                  {section.content.split("\n").map((paragraph, pIndex) =>
                    paragraph.trim().startsWith("•") ? (
                      <ul key={pIndex} className="ml-4 list-disc">
                        <li>{paragraph.replace("•", "").trim()}</li>
                      </ul>
                    ) : paragraph.trim() ? (
                      <p key={pIndex}>{paragraph.trim()}</p>
                    ) : null,
                  )}
                </div>
              </section>
            ))}
          </div>

          {annexures.length > 0 ? (
            <section className="mt-12 border-t border-border pt-8">
              <h2 className="mb-3 text-base font-semibold tracking-tight text-foreground">
                Annexures
              </h2>
              <ul className="ml-4 list-disc space-y-1 text-sm leading-relaxed text-muted-foreground">
                {annexures.map((a) => (
                  <li key={a.id}>
                    <span className="font-medium text-foreground">{a.code}</span> — {a.title}
                  </li>
                ))}
              </ul>
            </section>
          ) : null}

          <footer className="mt-12 border-t border-border pt-8 text-center text-xs text-muted-foreground">
            Generated by Waku Procurement AI · Confidential
          </footer>
        </article>
      </div>
    </ScrollArea>
  );
}
